[package]
name = "hired"
description = "Highlighting rust clone of ed"
version = "0.8.0"
homepage = "https://github.com/sidju/hired"
repository = "https://github.com/sidju/hired"
readme = "README.md"
categories = ["text-editors"]
keywords = ["ed", "syntax-highlighting", "cli"]
authors = ["sidju <contact@sidju.se>"]
license = "MIT"
edition = "2018"

include = [
  "assets/*",
  "**/*.rs",
  "Cargo.*",
]

[features]
debug = []

[dependencies]
add-ed = { version = "0.8", features = ["vecbuffer", "initial_input_data"] }
syntect = { version = "4.5", default-features = false, features = [
  "dump-load-rs", # for loading the compressed dump created by build.rs
  "parsing", # For the actual parsing
] }
crossterm = "0.19"
argh = "0.1"

[build-dependencies]
syntect = { version = "4.5" } # Onigura regex engine better handles inconsistencies in the syntax files
