[package]
name = "hired"
description = "Highlighting rust clone of ed"
version = "0.11.0"
homepage = "https://github.com/sidju/hired"
repository = "https://github.com/sidju/hired"
readme = "README.md"
categories = ["text-editors"]
keywords = ["ed", "syntax-highlighting", "cli"]
authors = ["sidju <contact@sidju.se>"]
license = "MIT"
edition = "2021"

include = [
  "assets/*",
  "**/*.rs",
  "Cargo.*",
]

[features]

[dependencies]
add-ed = { version = "0.11", features = ["local_io","initial_input_data"] }
termimad = "0.26"
syntect = { version = "5.1", default-features = false, features = [
  "regex-fancy", # use rust regex
  "parsing", # Includes loading the compressed dump created by build.rs
] }
# Avoid having support for bracketed paste = treat pasted input same as normal
crossterm = { version = "0.27", default-features = false, features = [
  "events"
]}
clap = { version = "4.4", features = ["derive", "env"] }

[build-dependencies]
syntect = { version = "5.1" } # Onigura regex engine better handles inconsistencies in the syntax files
