[package]
name = "hired"
description = "Highlighting rust clone of ed"
version = "0.9.0-alpha"
homepage = "https://github.com/sidju/hired"
repository = "https://github.com/sidju/hired"
readme = "README.md"
categories = ["text-editors"]
keywords = ["ed", "syntax-highlighting", "cli"]
authors = ["sidju <contact@sidju.se>"]
license = "MIT"
edition = "2018"

include = [
  "assets/*",
  "**/*.rs",
  "Cargo.*",
]

[features]
debug = []

[dependencies]
add-ed = { version = "0.9.0-alpha3", features = ["vecbuffer", "initial_input_data"] }
syntect = { version = "5", default-features = false, features = [
  "regex-fancy", # use rust regex
  "dump-load", # for loading the compressed dump created by build.rs
  "regex-syntax", "fnv" # for the actual parsing
] }
crossterm = "0.23"
clap = { version = "3", features = ["derive", "env"] }

[build-dependencies]
syntect = { version = "5" } # Onigura regex engine better handles inconsistencies in the syntax files
