[package]
name = "hired"
description = "Highlighting rust clone of ed"
version = "0.10.0"
homepage = "https://github.com/sidju/hired"
repository = "https://github.com/sidju/hired"
readme = "README.md"
categories = ["text-editors"]
keywords = ["ed", "syntax-highlighting", "cli"]
authors = ["sidju <contact@sidju.se>"]
license = "MIT"
edition = "2021"

include = [
  "assets/*",
  "**/*.rs",
  "Cargo.*",
]

[features]
debug = []

[dependencies]
add-ed = { version = "0.10", features = ["local_io","initial_input_data"] }
syntect = { version = "5", default-features = false, features = [
  "regex-fancy", # use rust regex
  "parsing", # Includes loading the compressed dump created by build.rs
] }
# Avoid having support for bracketed paste = treat pasted input same as normal
crossterm = { version = "0.26", default-features = false }
clap = { version = "4", features = ["derive", "env"] }

[build-dependencies]
syntect = { version = "5" } # Onigura regex engine better handles inconsistencies in the syntax files
